version: '3.7'
doctrine:
    dbal:
        driver: 'pdo_mysql'
services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - '3306'

    mailer:
        image: schickling/mailcatcher
        ports: 
            - 1025
            - 1080
